import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useMe } from "../src/hooks/reactQuery/useMe";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { isLoading, isError, error, data } = useMe();

  if (isLoading) return <>Loadiing...</>;
  if (isError) console.log(error);

  return (
    <div className={styles.container}>
      <Head>
        <title>NUMBLE:: 쿠팡 클론</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>유저 정보</h1>
        <p>{data?.id}</p>
        <p>{data?.name}</p>
        <p>{data?.email}</p>
        <p>{data?.phoneNumber}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/numble.png" alt="NUMBLE Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
